name: First
on:
  push:
    branches:
      main
      
jobs:

  First_Job:
    name: First job
    runs-on: ubuntu-latest

    steps:
    - name: step1
      run: echo "Hi Github Actions"
  Second_Job:
     name: Second job
     runs-on: ubuntu-latest
     steps:
     -  name: SecondStep
        run: echo "Second Step"
